### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by evanlikn** [elizaOS/eliza-starter#22]
TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async _BrowserService.initialize (file:///Users/yindexiang/Project/eliza/eliza-starter/node_modules/.pnpm/@ai16z+plugin-node@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.25_openai@4_xnvze5py6d4zozacsf6lj6gjnq/node_modules/@ai16z/plugin-node/dist/index.js:75:22)
    at async AgentRuntime.initialize (file:///Users/yindexiang/Project/eliza/eliza-starter/node_modules/.pnpm/@ai16z+eliza@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.25_openai@4.69.0__zs3rlrqgq2e6elojpkf74udsyi/node_modules/@ai16z/eliza/dist/index.js:2808:9)
    at async startAgent (file:///Users/yindexiang/Project/eliza/eliza-starter/src/index.ts:188:9)
    at async startAgents (file:///Users/yindexiang/Project/eliza/eliza-starter/src/index.ts:211:13) {
  [cause]: Error: connect ECONNREFUSED 0.0.0.0:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 443
  }
}

**Comment by wtfsayo** [comment]
closing since old!
