### ISSUE TITLE
ERROR When start

### ISSUE THREAD

**Issue by HowieChang7** [elizaOS/eliza-starter#32]
? ERRORS
   Error starting agent for character trump: 
   {} 

TypeError: cookiesArray.map is not a function
    at _ClientBase.setCookiesFromArray (file:///root/eliza-starter/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.20_opena_vz76klskf3wnoy3r5goewnopdu/node_modules/@ai16z/client-twitter/dist/index.js:1251:40)
    at _ClientBase.init (file:///root/eliza-starter/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.20_opena_vz76klskf3wnoy3r5goewnopdu/node_modules/@ai16z/client-twitter/dist/index.js:1006:18)
    at Object.start (file:///root/eliza-starter/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.20_opena_vz76klskf3wnoy3r5goewnopdu/node_modules/@ai16z/client-twitter/dist/index.js:1377:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async initializeClients (file:///root/eliza-starter/src/index.ts:133:32)
    at async startAgent (file:///root/eliza-starter/src/index.ts:193:25)
    at async startAgents (file:///root/eliza-starter/src/index.ts:216:13)
 ? ERRORS
   Error starting agents: 
   {} 

 ["◎ Chat started. Type 'exit' to quit."] 

<img width="893" alt="1735374274995" src="https://github.com/user-attachments/assets/0b957a94-146b-402e-9134-cf540415a6ee" />

**Comment by wtfsayo** [comment]
can you pull latest changes; this should have fixed- https://github.com/elizaOS/eliza-starter/pull/55

**Comment by HowieChang7** [comment]
自恋中，感觉比较幸福，勿扰，待会回复你
